cache:
  paths:
    -node_modules/

init:
  stage: init
  image: node:12.18.3
  script: 
    - npm install

deploy_prod:
  image: node:12.18.3
  stage: deploy_prod
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/caudio.git HEAD:master
    - echo "Deployed to production server"
  environment:
    name: production
    url: https://caudio.herokuapp.com
  only:
    - master