image: node:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: caudio
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: hello
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  paths:
    - node_modules/

stages:
  - init
  - test
  - deploy_prod

init:
  stage: init
  script:
    - npm install

test:
  stage: test
  script:
    - npm run ci-test

deploy_prod:
  stage: deploy_prod
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/caudio.git HEAD:master
    - echo "Deployed to prod server"
  environment:
    name: production
    url: https://caudio.herokuapp.com
  only:
    - master